In [1]:
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
df = pd.read_csv("train.csv")

In [3]:
X = pd.DataFrame()
X['sex'] = df['Sex']
X['age'] = df['Age']
X['pclass'] = df['Pclass']
X['sibsp'] = df['SibSp']
X['parch'] = df['Parch']
X['survived'] = df['Survived']

In [4]:
y = X['survived']
X = X.drop(['survived'], axis=1)

In [5]:
X['sex'] = pd.get_dummies(X.sex)['female']

In [6]:
X = X.join(pd.get_dummies(df.Pclass, prefix='pclass'))
X = X.drop(['pclass_1', 'pclass'], axis=1)

In [7]:
X

     sex  age  sibsp  parch  pclass_2  pclass_3
0      0   22      1      0         0         1
1      1   38      1      0         0         0
2      1   26      0      0         0         1
3      1   35      1      0         0         0
4      0   35      0      0         0         1
5      0  NaN      0      0         0         1
6      0   54      0      0         0         0
7      0    2      3      1         0         1
8      1   27      0      2         0         1
9      1   14      1      0         1         0
10     1    4      1      1         0         1
11     1   58      0      0         0         0
12     0   20      0      0         0         1
13     0   39      1      5         0         1
14     1   14      0      0         0         1
15     1   55      0      0         1         0
16     0    2      4      1         0         1
17     0  NaN      0      0         1         0
18     1   31      1      0         0         1
19     1  NaN      0      0         0         1
20     0   35      0      0         1         0
21     0   34      0      0         1         0
22     1   15      0      0         0         1
23     0   28      0      0         0         0
24     1    8      3      1         0         1
25     1   38      1      5         0         1
26     0  NaN      0      0         0         1
27     0   19      3      2         0         0
28     1  NaN      0      0         0         1
29     0  NaN      0      0         0         1
..   ...  ...    ...    ...       ...       ...
861    0   21      1      0         1         0
862    1   48      0      0         0         0
863    1  NaN      8      2         0         1
864    0   24      0      0         1         0
865    1   42      0      0         1         0
866    1   27      1      0         1         0
867    0   31      0      0         0         0
868    0  NaN      0      0         0         1
869    0    4      1      1         0         1
870    0   26      0      0         0         1
871    1   47      1      1         0         0
872    0   33      0      0         0         0
873    0   47      0      0         0         1
874    1   28      1      0         1         0
875    1   15      0      0         0         1
876    0   20      0      0         0         1
877    0   19      0      0         0         1
878    0  NaN      0      0         0         1
879    1   56      0      1         0         0
880    1   25      0      1         1         0
881    0   33      0      0         0         1
882    1   22      0      0         0         1
883    0   28      0      0         1         0
884    0   25      0      0         0         1
885    1   39      0      5         0         1
886    0   27      0      0         1         0
887    1   19      0      0         0         0
888    1  NaN      1      2         0         1
889    0   26      0      0         0         0
890    0   32      0      0         0         1

[891 rows x 6 columns]

In [9]:
meanAge = X['age'].mean()
X['age'] = X['age'].fillna(meanAge)

In [10]:
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X= scaler.fit_transform(X)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(penalty='l2', C=10)

In [13]:
model.fit(X_train, y_train)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)

In [14]:
print "Logistic accuracy is %2.2f" % accuracy_score(y_test,model.predict(X_test))

NameError: name 'accuracy_score' is not defined